Neos:
  Neos:
    fusion:
      autoInclude:
        'Carbon.IncludeAssets': true
  Fusion:
    defaultContext:
      Carbon.IncludeAssets: 'Carbon\IncludeAssets\Eel\Helper\IncludeAssetsHelper'

# You can pass the filenames as string (comma separated) or as an array
#  * internal: Just the filename e.g. "Main.js,Slider.css"
#  * external: e.g. //ajax.googleapis.com/...
#  * If you want to add attributes, add it with square brackets e.g. Filename.js[async data-prop data-attr="true"]
#  * CSS can also be loaded asynchron: Just add async as attribute e.g. Filename.css[async class="classname"]
#  * If you want a file included inline, just add the attribute "inline": e.g. Filename.css[inline]
#  * If you are not able to have a file extension you can force the type with braces e.g. Filename(css) / Filename[async](js)

Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: false
    GoogleFonts: null  # e.g. 'Lato|Open+Sans:400,700', for async loading e.g. 'Lato|Open+Sans:400,700[async]'
    # Default settings
    Default:
      Package: SitePackage
      CacheBuster: true
      ConditionPrototype: null
      Path:
        Inline:
          CSS: 'Private/Templates/InlineAssets'
          JS: 'Private/Templates/InlineAssets'
          MJS: 'Private/Templates/InlineAssets'
        File:
          CSS: 'Public/Styles'
          JS: 'Public/Scripts'
          MJS: 'Public/Modules'
      # Asset files who get's loaded in live and backend view
      General:
        Head: null
        Body: null
      # Asset files who get's loaded only in the backend
      Backend:
        Head: null
        Body: null
      # Asset files who get's loaded only in the live view
      Live:
        Head: null
        Body: null
#    Packages:
#    Packages keys get sorted first by numbers, then by characters.
