Neos:
  Neos:
    fusion:
      autoInclude:
        'Carbon.IncludeAssets': true

# You can pass the filenames as string (comma separated) or as an array
#  * internal: Just the filename e.g. "Main.js,Slider.css"
#  * external: e.g. //ajax.googleapis.com/...
#  * If you want to add attributes, add it with square brackets e.g. Filename.js[async data-prop data-attr="true"]
#  * If you want a file included inline, just add the attribute "inline": e.g. Filename.css[inline]
#  * If you are not able to have a file extension you can force the type with braces e.g. Filename(css) / Filename[async](js)

Carbon:
  IncludeAssets:
    GoogleFonts: null  # e.g. 'Lato|Open+Sans:400,700'
    AssetPackage: null # If not set, the siteResourcesPackageKey from the currentSite will be used
    LoadCSSAsynchron: false
    LoadJSforCSSAsynchron: false
    Path:
      Inline:
        CSS: 'Private/Templates/InlineAssets'
        JS: 'Private/Templates/InlineAssets'
      File:
        CSS: 'Public/Styles'
        JS: 'Public/Scripts'
    # Asset files who get's loaded in live and backend view
    General:
      Head: null
      Body: null
    # Asset files who get's loaded only in the backend
    Backend:
      Head: null
      Body: null
    # Asset files who get's loaded only in the live view
    Live:
      Head: null
      Body: null
