# You can pass the filenames as string (comma separated) or as an array
#  * internal: Just the filename e.g. "Main.js,Slider.css"
#  * external: e.g. //ajax.googleapis.com/...
#  * If you want to add attributes, add it with square brackets e.g. Filename.js[async data-prop data-attr="true"]
#  * CSS can also be loaded asynchron: Just add async as attribute e.g. Filename.css[async class="classname"]
#  * If you want a file included inline, just add the attribute "inline": e.g. Filename.css[inline]
#  * If you are not able to have a file extension you can force the type with braces e.g. Filename(css) / Filename[async](js) / Module(mjs)

Carbon:
  IncludeAssets:
    LoadJSforCSSAsynchron: true
    GoogleFonts: null # e.g. 'Lato|Open+Sans:400,700', for async loading e.g. 'Lato|Open+Sans:400,700[async]'
    ResourceHints:
      DnsPrefetch: [] # Add <link rel="dns-prefetch" href="Entry" />
      Preconnect: [] # Add <link rel="preconnect" href="Entry" />
      Prefetch: [] # Add <link rel="prefetch" href="Entry" />
      Preload: [] # Add <link rel="preload" href="Entry" /> Example entry: 'https://domain.tld/resource.js[as="script" crossorigin="anonymos"]'
      Prerender: [] # Add <link rel="prerender" href="Entry" /> Example entry: 'https://domain.tld'
      ModulePreload: [] # Add <link rel="modulePpreload" href="Entry" /> Example entry: 'https://domain.tld/module.mjs'
    # Default settings
    Default:
      Package: SitePackage
      CacheBuster: true
      DisableCacheBusterForPreloadAsset: true
      ConditionPrototype: null
      Wrapper: null
      Order: 'General,Backend,Live'
      Path:
        Inline:
          CSS: 'Private/Templates/InlineAssets'
          JS: 'Private/Templates/InlineAssets'
          MJS: 'Private/Templates/InlineAssets'
          HTML: 'Private/Templates/InlineAssets'
        File:
          CSS: 'Public/Styles'
          JS: 'Public/Scripts'
          MJS: 'Public/Modules'
          PRELOADASSET: 'Public/Assets'
          PRELOADCSS: 'Public/Styles'
          PRELOADSCRIPT: 'Public/Scripts'
          MODULEPRELOAD: 'Public/Modules'
      # Asset files who get's loaded in live and backend view
      General:
        HeadStart: null
        Head: null
        BodyStart: null
        Body: null
      # Asset files who get's loaded only in the backend
      Backend:
        HeadStart: null
        Head: null
        BodyStart: null
        Body: null
      # Asset files who get's loaded only in the live view
      Live:
        HeadStart: null
        Head: null
        BodyStart: null
        Body: null
#    Packages:
#    Packages keys get sorted first by numbers, then by characters.
